import os
import json
import logging
import gradio as gr
from typing import Optional, Tuple, Dict, Any
from github import Github
from adventure_generator import generate_story
from update_manifest import update_manifest

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

def process_and_save_story(topic: str, level: str, length: str, age_range: str) -> Tuple[str, Optional[str], Optional[Dict[str, Any]]]:
    """
    Orchestrates story generation, saving, and manifest update.

    Args:
        topic: The description of the story to generate.
        level: The CEFR English level.
        length: The length of the story.
        age_range: The age range of the reader.

    Returns:
        A tuple of (status message, file path for download, story data).
    """
    try:
        story_data = generate_story(topic, level, length, age_range)
        if not story_data:
            return "Error: Could not generate story. Please check the logs for details.", None, None

        # Ensure docs and docs/stories directories exist
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        docs_dir = os.path.join(base_dir, "docs")
        stories_dir = os.path.join(docs_dir, "stories")
        os.makedirs(stories_dir, exist_ok=True)

        # Generate a filename for the story
        title = story_data.get("title", "story")
        story_id = "".join(x for x in title if x.isalnum())[:20].lower() or "story"
        filename = f"{story_id}_{int(os.getpid())}.json"
        story_path = os.path.join(stories_dir, filename)

        # Save the story JSON
        with open(story_path, "w") as f:
            json.dump(story_data, f, indent=2)

        # Update manifest.json automatically by scanning stories directory
        update_manifest()

        # Ensure index.html is initialized from template
        template_path = os.path.join(os.path.dirname(__file__), "templates", "story_template.html")
        index_path = os.path.join(docs_dir, "index.html")

        if os.path.exists(template_path):
            with open(template_path, "r") as f:
                template_content = f.read()

            with open(index_path, "w") as f:
                f.write(template_content)

        return f"Story '{story_data.get('title')}' generated successfully!", story_path, story_data
    except Exception as e:
        logger.exception("Error in process_and_save_story")
        return f"An unexpected error occurred: {str(e)}", None, None

def create_github_pr(story_data: Optional[Dict[str, Any]]) -> str:
    """
    Creates a Pull Request on GitHub with the new story.
    """
    if not story_data:
        return "Error: No story data found. Please generate a story first."

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        return "Error: GITHUB_TOKEN environment variable not set."

    repo_name = os.environ.get("GITHUB_REPO", "dgaida/choose_adventure")

    try:
        g = Github(token)
        repo = g.get_repo(repo_name)

        # Get default branch
        main_branch = repo.default_branch
        sb = repo.get_branch(main_branch)

        # Create a new branch
        title = story_data.get("title", "story")
        story_id = "".join(x for x in title if x.isalnum())[:20].lower() or "story"
        branch_name = f"story-{story_id}-{os.getpid()}"

        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sb.commit.sha)

        # 1. Create the story JSON file
        filename = f"{story_id}.json"
        story_path = f"docs/stories/{filename}"
        content = json.dumps(story_data, indent=2)
        repo.create_file(story_path, f"Add story: {title}", content, branch=branch_name)

        # 2. Update manifest.json
        manifest_path = "docs/stories/manifest.json"
        manifest_file = repo.get_contents(manifest_path, ref=branch_name)
        manifest_data = json.loads(manifest_file.decoded_content.decode())

        # Add new story to manifest
        manifest_data["stories"].append({
            "title": title,
            "filename": filename
        })
        # Sort manifest stories by title
        manifest_data["stories"] = sorted(manifest_data["stories"], key=lambda x: x["title"])

        updated_manifest_content = json.dumps(manifest_data, indent=2)
        repo.update_file(manifest_path, "Update manifest.json", updated_manifest_content, manifest_file.sha, branch=branch_name)

        # 3. Create Pull Request
        pr = repo.create_pull(
            title=f"New Story: {title}",
            body=f"This PR adds a new story titled '{title}' generated by the AI.",
            head=branch_name,
            base=main_branch
        )

        return f"Pull Request created successfully: {pr.html_url}"
    except Exception as e:
        logger.exception("Error creating Pull Request")
        return f"Error creating Pull Request: {str(e)}"

# Create Gradio UI
with gr.Blocks(title="Adventure Story Generator") as demo:
    gr.Markdown("# 🗺️ Adventure Story Generator")
    gr.Markdown("Create branching stories for English learners.")

    story_state = gr.State()

    with gr.Row():
        with gr.Column():
            default_topic = "Create a branching story set in the universe of the 'Warriors' book series by Erin Hunter. It should involve a young apprentice's first hunt and a mysterious prophecy. The story should be appropriate for English learners."
            topic_input = gr.Textbox(label="Story Description", lines=10, value=default_topic)
        with gr.Column():
            level_input = gr.Dropdown(label="English Level", choices=["A1", "A2", "B1", "B2", "C1", "C2"], value="B1")
            length_input = gr.Dropdown(
                label="Story Length",
                choices=["short (15-20 nodes)", "medium (20-25 nodes)", "long (25-30 nodes)"],
                value="short (15-20 nodes)"
            )
            age_input = gr.Dropdown(
                label="Reader Age Range",
                choices=["6-12", "12-18", "18-30", "30-50", "50+"],
                value="12-18"
            )

    generate_btn = gr.Button("Generate Story")

    with gr.Row():
        output_text = gr.Textbox(label="Status")
        download_file = gr.File(label="Download Story JSON")

    pr_btn = gr.Button("Create Pull Request on GitHub", variant="primary")
    pr_status = gr.Textbox(label="PR Status")

    generate_btn.click(
        fn=process_and_save_story,
        inputs=[topic_input, level_input, length_input, age_input],
        outputs=[output_text, download_file, story_state]
    )

    pr_btn.click(
        fn=create_github_pr,
        inputs=[story_state],
        outputs=pr_status
    )

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 7860))
    demo.launch(server_name="0.0.0.0", server_port=port)
